apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jcqyzcd0v-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:2b70b463e1c8733a081e71caf68fa07e1a7b947b@sha256:fabc361952d9fd6334be99acbb15abda46d8674f389f4e1cbcc6df8dbff0c365
          name: container-image
